Purpose: Atheros regulatory domain constants
\ See license at end of file

headers
hex

00 constant NO_ENUMRD
03 constant NULL1_WORLD
07 constant NULL1_ETSIB
08 constant NULL1_ETSIC
10 constant FCC1_FCCA
11 constant FCC1_WORLD
12 constant FCC4_FCCA
13 constant FCC5_FCCA
14 constant FCC6_FCCA

20 constant FCC2_FCCA
21 constant FCC2_WORLD
22 constant FCC2_ETSIC
23 constant FCC6_WORLD
31 constant FRANCE_RES
3a constant FCC3_FCCA
3b constant FCC3_WORLD

37 constant ETSI1_WORLD
32 constant ETSI3_ETSIA
35 constant ETSI2_WORLD
36 constant ETSI3_WORLD
30 constant ETSI4_WORLD
38 constant ETSI4_ETSIC
39 constant ETSI5_WORLD
34 constant ETSI6_WORLD
33 constant ETSI_RESERVED

40 constant MKK1_MKKA
41 constant MKK1_MKKB
42 constant APL4_WORLD
43 constant MKK2_MKKA
44 constant APL_RESERVED
45 constant APL2_WORLD
46 constant APL2_APLC
47 constant APL3_WORLD
48 constant MKK1_FCCA
49 constant APL2_APLD
4a constant MKK1_MKKA1
4b constant MKK1_MKKA2
4c constant MKK1_MKKC

50 constant APL3_FCCA
52 constant APL1_WORLD
53 constant APL1_FCCA
54 constant APL1_APLA
55 constant APL1_ETSIC
56 constant APL2_ETSIC
58 constant APL5_WORLD
5b constant APL6_WORLD
5c constant APL7_FCCA 
5d constant APL8_WORLD
5e constant APL9_WORLD

60 constant WOR0_WORLD
61 constant WOR1_WORLD
62 constant WOR2_WORLD
63 constant WOR3_WORLD
64 constant WOR4_WORLD
65 constant WOR5_ETSIC

66 constant WOR01_WORLD
67 constant WOR02_WORLD
68 constant EU1_WORLD

69 constant WOR9_WORLD
6a constant WORA_WORLD
6b constant WORB_WORLD

80 constant MKK3_MKKB
81 constant MKK3_MKKA2
82 constant MKK3_MKKC 

83 constant MKK4_MKKB 
84 constant MKK4_MKKA2
85 constant MKK4_MKKC 

86 constant MKK5_MKKB 
87 constant MKK5_MKKA2
88 constant MKK5_MKKC 

89 constant MKK6_MKKB 
8a constant MKK6_MKKA2
8b constant MKK6_MKKC 

8c constant MKK7_MKKB 
8d constant MKK7_MKKA2
8e constant MKK7_MKKC 

8f constant MKK8_MKKB 
90 constant MKK8_MKKA2
91 constant MKK8_MKKC 

92 constant MKK14_MKKA1
93 constant MKK15_MKKA1

d0 constant MKK10_FCCA 
d1 constant MKK10_MKKA1
d2 constant MKK10_MKKC 
d3 constant MKK10_MKKA2

d4 constant MKK11_MKKA 
d5 constant MKK11_FCCA 
d6 constant MKK11_MKKA1
d7 constant MKK11_MKKC 
d8 constant MKK11_MKKA2

d9 constant MKK12_MKKA 
da constant MKK12_FCCA 
db constant MKK12_MKKA1
dc constant MKK12_MKKC 
dd constant MKK12_MKKA2

de constant MKK13_MKKB 

f0 constant MKK3_MKKA 
f1 constant MKK3_MKKA1
f2 constant MKK3_FCCA 
f3 constant MKK4_MKKA 
f4 constant MKK4_MKKA1
f5 constant MKK4_FCCA 
f6 constant MKK9_MKKA 
f7 constant MKK10_MKKA
f8 constant MKK6_MKKA1
f9 constant MKK6_FCCA 
fa constant MKK7_MKKA1
fb constant MKK7_FCCA 
fc constant MKK9_FCCA 
fd constant MKK9_MKKA1
fe constant MKK9_MKKC 
ff constant MKK9_MKKA2

0199 constant WORLD
01ff constant DEBUG_REG_DMN

40 constant CTL_MKK
30 constant CTL_ETSI
ff constant NO_CTL   

\ Regpair to CTL band mapping
create regDomainPairs
here
	\ regpair , 5 GHz CTL , 2 GHz CTL 
	NO_ENUMRD , DEBUG_REG_DMN , DEBUG_REG_DMN ,
	NULL1_WORLD , NO_CTL , CTL_ETSI ,
	NULL1_ETSIB , NO_CTL , CTL_ETSI ,
	NULL1_ETSIC , NO_CTL , CTL_ETSI ,

	FCC2_FCCA , CTL_FCC , CTL_FCC ,
	FCC2_WORLD , CTL_FCC , CTL_ETSI ,
	FCC2_ETSIC , CTL_FCC , CTL_ETSI ,
	FCC3_FCCA , CTL_FCC , CTL_FCC ,
	FCC3_WORLD , CTL_FCC , CTL_ETSI ,
	FCC4_FCCA , CTL_FCC , CTL_FCC ,
	FCC5_FCCA , CTL_FCC , CTL_FCC ,
	FCC6_FCCA , CTL_FCC , CTL_FCC ,
	FCC6_WORLD , CTL_FCC , CTL_ETSI ,

	ETSI1_WORLD , CTL_ETSI , CTL_ETSI ,
	ETSI2_WORLD , CTL_ETSI , CTL_ETSI ,
	ETSI3_WORLD , CTL_ETSI , CTL_ETSI ,
	ETSI4_WORLD , CTL_ETSI , CTL_ETSI ,
	ETSI5_WORLD , CTL_ETSI , CTL_ETSI ,
	ETSI6_WORLD , CTL_ETSI , CTL_ETSI ,

	ETSI3_ETSIA , CTL_ETSI , CTL_ETSI ,
	FRANCE_RES , CTL_ETSI , CTL_ETSI ,

	FCC1_WORLD , CTL_FCC , CTL_ETSI ,
	FCC1_FCCA , CTL_FCC , CTL_FCC ,
	APL1_WORLD , CTL_FCC , CTL_ETSI ,
	APL2_WORLD , CTL_FCC , CTL_ETSI ,
	APL3_WORLD , CTL_FCC , CTL_ETSI ,
	APL4_WORLD , CTL_FCC , CTL_ETSI ,
	APL5_WORLD , CTL_FCC , CTL_ETSI ,
	APL6_WORLD , CTL_ETSI , CTL_ETSI ,
	APL8_WORLD , CTL_ETSI , CTL_ETSI ,
	APL9_WORLD , CTL_ETSI , CTL_ETSI ,

	APL3_FCCA , CTL_FCC , CTL_FCC ,
	APL7_FCCA , CTL_FCC , CTL_FCC ,
	APL1_ETSIC , CTL_FCC , CTL_ETSI ,
	APL2_ETSIC , CTL_FCC , CTL_ETSI ,
	APL2_APLD , CTL_FCC , NO_CTL ,

	MKK1_MKKA , CTL_MKK , CTL_MKK ,
	MKK1_MKKB , CTL_MKK , CTL_MKK ,
	MKK1_FCCA , CTL_MKK , CTL_FCC ,
	MKK1_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK1_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK1_MKKC , CTL_MKK , CTL_MKK ,

	MKK2_MKKA , CTL_MKK , CTL_MKK ,
	MKK3_MKKA , CTL_MKK , CTL_MKK ,
	MKK3_MKKB , CTL_MKK , CTL_MKK ,
	MKK3_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK3_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK3_MKKC , CTL_MKK , CTL_MKK ,
	MKK3_FCCA , CTL_MKK , CTL_FCC ,

	MKK4_MKKA , CTL_MKK , CTL_MKK ,
	MKK4_MKKB , CTL_MKK , CTL_MKK ,
	MKK4_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK4_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK4_MKKC , CTL_MKK , CTL_MKK ,
	MKK4_FCCA , CTL_MKK , CTL_FCC ,

	MKK5_MKKB , CTL_MKK , CTL_MKK ,
	MKK5_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK5_MKKC , CTL_MKK , CTL_MKK ,

	MKK6_MKKB , CTL_MKK , CTL_MKK ,
	MKK6_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK6_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK6_MKKC , CTL_MKK , CTL_MKK ,
	MKK6_FCCA , CTL_MKK , CTL_FCC ,

	MKK7_MKKB , CTL_MKK , CTL_MKK ,
	MKK7_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK7_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK7_MKKC , CTL_MKK , CTL_MKK ,
	MKK7_FCCA , CTL_MKK , CTL_FCC ,

	MKK8_MKKB , CTL_MKK , CTL_MKK ,
	MKK8_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK8_MKKC , CTL_MKK , CTL_MKK ,

	MKK9_MKKA , CTL_MKK , CTL_MKK ,
	MKK9_FCCA , CTL_MKK , CTL_FCC ,
	MKK9_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK9_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK9_MKKC , CTL_MKK , CTL_MKK ,

	MKK10_MKKA , CTL_MKK , CTL_MKK ,
	MKK10_FCCA , CTL_MKK , CTL_FCC ,
	MKK10_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK10_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK10_MKKC , CTL_MKK , CTL_MKK ,

	MKK11_MKKA , CTL_MKK , CTL_MKK ,
	MKK11_FCCA , CTL_MKK , CTL_FCC ,
	MKK11_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK11_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK11_MKKC , CTL_MKK , CTL_MKK ,

	MKK12_MKKA , CTL_MKK , CTL_MKK ,
	MKK12_FCCA , CTL_MKK , CTL_FCC ,
	MKK12_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK12_MKKA2 , CTL_MKK , CTL_MKK ,
	MKK12_MKKC , CTL_MKK , CTL_MKK ,

	MKK13_MKKB , CTL_MKK , CTL_MKK ,
	MKK14_MKKA1 , CTL_MKK , CTL_MKK ,
	MKK15_MKKA1 , CTL_MKK , CTL_MKK ,

	WOR0_WORLD , NO_CTL , NO_CTL ,
	WOR1_WORLD , NO_CTL , NO_CTL ,
	WOR2_WORLD , NO_CTL , NO_CTL ,
	WOR3_WORLD , NO_CTL , NO_CTL ,
	WOR4_WORLD , NO_CTL , NO_CTL ,
	WOR5_ETSIC , NO_CTL , NO_CTL ,
	WOR01_WORLD , NO_CTL , NO_CTL ,
	WOR02_WORLD , NO_CTL , NO_CTL ,
	EU1_WORLD , NO_CTL , NO_CTL ,
	WOR9_WORLD , NO_CTL , NO_CTL ,
	WORA_WORLD , NO_CTL , NO_CTL ,
	WORB_WORLD , NO_CTL , NO_CTL ,
here swap - 3 /n* / constant #regDomainPairs

0 constant CTRY_DEFAULT
1ff constant CTRY_DEBUG

\ Country codes
decimal
   8 constant CTRY_ALBANIA
  12 constant CTRY_ALGERIA
  32 constant CTRY_ARGENTINA
  51 constant CTRY_ARMENIA
 533 constant CTRY_ARUBA
  36 constant CTRY_AUSTRALIA
  40 constant CTRY_AUSTRIA
  31 constant CTRY_AZERBAIJAN

  48 constant CTRY_BAHRAIN
  50 constant CTRY_BANGLADESH
  52 constant CTRY_BARBADOS
 112 constant CTRY_BELARUS
  56 constant CTRY_BELGIUM
  84 constant CTRY_BELIZE
  68 constant CTRY_BOLIVIA
  70 constant CTRY_BOSNIA_HERZ
  76 constant CTRY_BRAZIL
  96 constant CTRY_BRUNEI_DARUSSALAM
 100 constant CTRY_BULGARIA

 116 constant CTRY_CAMBODIA
 124 constant CTRY_CANADA
 152 constant CTRY_CHILE
 156 constant CTRY_CHINA
 170 constant CTRY_COLOMBIA
 188 constant CTRY_COSTA_RICA
 190 constant CTRY_CROATIA
 196 constant CTRY_CYPRUS
 203 constant CTRY_CZECH

 208 constant CTRY_DENMARK
 214 constant CTRY_DOMINICAN_REPUBLIC

 218 constant CTRY_ECUADOR
 818 constant CTRY_EGYPT
 222 constant CTRY_EL_SALVADOR
 233 constant CTRY_ESTONIA

 234 constant CTRY_FAEROE_ISLANDS
 246 constant CTRY_FINLAND
 250 constant CTRY_FRANCE

 268 constant CTRY_GEORGIA
 276 constant CTRY_GERMANY
 300 constant CTRY_GREECE 
 304 constant CTRY_GREENLAND
 308 constant CTRY_GRENEDA 
 316 constant CTRY_GUAM
 320 constant CTRY_GUATEMALA

 332 constant CTRY_HAITI
 340 constant CTRY_HONDURAS
 344 constant CTRY_HONG_KONG
 348 constant CTRY_HUNGARY

 352 constant CTRY_ICELAND
 356 constant CTRY_INDIA 
 360 constant CTRY_INDONESIA 
 365 constant CTRY_IRAN 
 368 constant CTRY_IRAQ 
 372 constant CTRY_IRELAND
 376 constant CTRY_ISRAEL 
 380 constant CTRY_ITALY 

 388 constant CTRY_JAMAICA
 392 constant CTRY_JAPAN
 400 constant CTRY_JORDAN

 398 constant CTRY_KAZAKHSTAN
 404 constant CTRY_KENYA 
 408 constant CTRY_KOREA_NORTH
 410 constant CTRY_KOREA_ROC 
 411 constant CTRY_KOREA_ROC2
 412 constant CTRY_KOREA_ROC3
 414 constant CTRY_KUWAIT 

 428 constant CTRY_LATVIA
 422 constant CTRY_LEBANON
 434 constant CTRY_LIBYA 
 438 constant CTRY_LIECHTENSTEIN
 440 constant CTRY_LITHUANIA 
 442 constant CTRY_LUXEMBOURG

 446 constant CTRY_MACAU 
 807 constant CTRY_MACEDONIA
 458 constant CTRY_MALAYSIA 
 470 constant CTRY_MALTA 
 484 constant CTRY_MEXICO
 492 constant CTRY_MONACO
 504 constant CTRY_MOROCCO

 524 constant CTRY_NEPAL
 528 constant CTRY_NETHERLANDS
 530 constant CTRY_NETHERLANDS_ANTILLES
 554 constant CTRY_NEW_ZEALAND
 558 constant CTRY_NICARAGUA 
 578 constant CTRY_NORWAY

 512 constant CTRY_OMAN

 586 constant CTRY_PAKISTAN
 591 constant CTRY_PANAMA 
 598 constant CTRY_PAPUA_NEW_GUINEA
 600 constant CTRY_PARAGUAY
 604 constant CTRY_PERU 
 608 constant CTRY_PHILIPPINES
 616 constant CTRY_POLAND
 620 constant CTRY_PORTUGAL
 630 constant CTRY_PUERTO_RICO

 634 constant CTRY_QATAR

 642 constant CTRY_ROMANIA
 643 constant CTRY_RUSSIA

 682 constant CTRY_SAUDI_ARABIA
 891 constant CTRY_SERBIA_MONTENEGRO 
 702 constant CTRY_SINGAPORE
 703 constant CTRY_SLOVAKIA 
 705 constant CTRY_SLOVENIA 
 710 constant CTRY_SOUTH_AFRICA
 724 constant CTRY_SPAIN 
 144 constant CTRY_SRI_LANKA
 752 constant CTRY_SWEDEN 
 756 constant CTRY_SWITZERLAND
 760 constant CTRY_SYRIA 

 158 constant CTRY_TAIWAN
 764 constant CTRY_THAILAND
 780 constant CTRY_TRINIDAD_Y_TOBAGO
 788 constant CTRY_TUNISIA 
 792 constant CTRY_TURKEY 

 784 constant CTRY_UAE
 804 constant CTRY_UKRAINE
 826 constant CTRY_UNITED_KINGDOM 
 840 constant CTRY_UNITED_STATES
 842 constant CTRY_UNITED_STATES_FCC49
 858 constant CTRY_URUGUAY 
 860 constant CTRY_UZBEKISTAN 

 862 constant CTRY_VENEZUELA 
 704 constant CTRY_VIET_NAM 

 877 constant CTRY_YEMEN

 716 constant CTRY_ZIMBABWE 

 393 constant CTRY_JAPAN1 
 394 constant CTRY_JAPAN2 
 395 constant CTRY_JAPAN3 
 396 constant CTRY_JAPAN4 
 397 constant CTRY_JAPAN5 
4006 constant CTRY_JAPAN6 
4007 constant CTRY_JAPAN7 
4008 constant CTRY_JAPAN8 
4009 constant CTRY_JAPAN9 
4010 constant CTRY_JAPAN10
4011 constant CTRY_JAPAN11
4012 constant CTRY_JAPAN12
4013 constant CTRY_JAPAN13
4014 constant CTRY_JAPAN14
4015 constant CTRY_JAPAN15
4016 constant CTRY_JAPAN16
4017 constant CTRY_JAPAN17
4018 constant CTRY_JAPAN18
4019 constant CTRY_JAPAN19
4020 constant CTRY_JAPAN20
4021 constant CTRY_JAPAN21
4022 constant CTRY_JAPAN22
4023 constant CTRY_JAPAN23
4024 constant CTRY_JAPAN24
4025 constant CTRY_JAPAN25
4026 constant CTRY_JAPAN26
4027 constant CTRY_JAPAN27
4028 constant CTRY_JAPAN28
4029 constant CTRY_JAPAN29
4030 constant CTRY_JAPAN30
4031 constant CTRY_JAPAN31
4032 constant CTRY_JAPAN32
4033 constant CTRY_JAPAN33
4034 constant CTRY_JAPAN34
4035 constant CTRY_JAPAN35
4036 constant CTRY_JAPAN36
4037 constant CTRY_JAPAN37
4038 constant CTRY_JAPAN38
4039 constant CTRY_JAPAN39
4040 constant CTRY_JAPAN40
4041 constant CTRY_JAPAN41
4042 constant CTRY_JAPAN42
4043 constant CTRY_JAPAN43
4044 constant CTRY_JAPAN44
4045 constant CTRY_JAPAN45
4046 constant CTRY_JAPAN46
4047 constant CTRY_JAPAN47
4048 constant CTRY_JAPAN48
4049 constant CTRY_JAPAN49
4050 constant CTRY_JAPAN50
4051 constant CTRY_JAPAN51
4052 constant CTRY_JAPAN52
4053 constant CTRY_JAPAN53
4054 constant CTRY_JAPAN54
4055 constant CTRY_JAPAN55
4056 constant CTRY_JAPAN56
4057 constant CTRY_JAPAN57
4058 constant CTRY_JAPAN58
4059 constant CTRY_JAPAN59

5000 constant CTRY_AUSTRALIA2
5001 constant CTRY_CANADA2 
5002 constant CTRY_BELGIUM2
hex

create allCountries
here
	CTRY_DEBUG  , NO_ENUMRD  , " DB" $,
	CTRY_DEFAULT  , FCC1_FCCA  , " CO" $,
	CTRY_ALBANIA  , NULL1_WORLD  , " AL" $,
	CTRY_ALGERIA  , NULL1_WORLD  , " DZ" $,
	CTRY_ARGENTINA  , FCC3_WORLD  , " AR" $,
	CTRY_ARMENIA  , ETSI4_WORLD  , " AM" $,
	CTRY_ARUBA  , ETSI1_WORLD  , " AW" $,
	CTRY_AUSTRALIA  , FCC2_WORLD  , " AU" $,
	CTRY_AUSTRALIA2  , FCC6_WORLD  , " AU" $,
	CTRY_AUSTRIA  , ETSI1_WORLD  , " AT" $,
	CTRY_AZERBAIJAN  , ETSI4_WORLD  , " AZ" $,
	CTRY_BAHRAIN  , APL6_WORLD  , " BH" $,
	CTRY_BANGLADESH  , NULL1_WORLD  , " BD" $,
	CTRY_BARBADOS  , FCC2_WORLD  , " BB" $,
	CTRY_BELARUS  , ETSI1_WORLD  , " BY" $,
	CTRY_BELGIUM  , ETSI1_WORLD  , " BE" $,
	CTRY_BELGIUM2  , ETSI4_WORLD  , " BL" $,
	CTRY_BELIZE  , APL1_ETSIC  , " BZ" $,
	CTRY_BOLIVIA  , APL1_ETSIC  , " BO" $,
	CTRY_BOSNIA_HERZ  , ETSI1_WORLD  , " BA" $,
	CTRY_BRAZIL  , FCC3_WORLD  , " BR" $,
	CTRY_BRUNEI_DARUSSALAM  , APL1_WORLD  , " BN" $,
	CTRY_BULGARIA  , ETSI6_WORLD  , " BG" $,
	CTRY_CAMBODIA  , ETSI1_WORLD  , " KH" $,
	CTRY_CANADA  , FCC3_FCCA  , " CA" $,
	CTRY_CANADA2  , FCC6_FCCA  , " CA" $,
	CTRY_CHILE  , APL6_WORLD  , " CL" $,
	CTRY_CHINA  , APL1_WORLD  , " CN" $,
	CTRY_COLOMBIA  , FCC1_FCCA  , " CO" $,
	CTRY_COSTA_RICA  , FCC1_WORLD  , " CR" $,
	CTRY_CROATIA  , ETSI1_WORLD  , " HR" $,
	CTRY_CYPRUS  , ETSI1_WORLD  , " CY" $,
	CTRY_CZECH  , ETSI3_WORLD  , " CZ" $,
	CTRY_DENMARK  , ETSI1_WORLD  , " DK" $,
	CTRY_DOMINICAN_REPUBLIC  , FCC1_FCCA  , " DO" $,
	CTRY_ECUADOR  , FCC1_WORLD  , " EC" $,
	CTRY_EGYPT  , ETSI3_WORLD  , " EG" $,
	CTRY_EL_SALVADOR  , FCC1_WORLD  , " SV" $,
	CTRY_ESTONIA  , ETSI1_WORLD  , " EE" $,
	CTRY_FINLAND  , ETSI1_WORLD  , " FI" $,
	CTRY_FRANCE  , ETSI1_WORLD  , " FR" $,
	CTRY_GEORGIA  , ETSI4_WORLD  , " GE" $,
	CTRY_GERMANY  , ETSI1_WORLD  , " DE" $,
	CTRY_GREECE  , ETSI1_WORLD  , " GR" $,
	CTRY_GREENLAND  , ETSI1_WORLD  , " GL" $,
	CTRY_GRENEDA  , FCC3_FCCA  , " GD" $,
	CTRY_GUAM  , FCC1_FCCA  , " GU" $,
	CTRY_GUATEMALA  , FCC1_FCCA  , " GT" $,
	CTRY_HAITI  , ETSI1_WORLD  , " HT" $,
	CTRY_HONDURAS  , NULL1_WORLD  , " HN" $,
	CTRY_HONG_KONG  , FCC3_WORLD  , " HK" $,
	CTRY_HUNGARY  , ETSI1_WORLD  , " HU" $,
	CTRY_ICELAND  , ETSI1_WORLD  , " IS" $,
	CTRY_INDIA  , APL6_WORLD  , " IN" $,
	CTRY_INDONESIA  , NULL1_WORLD  , " ID" $,
	CTRY_IRAN  , APL1_WORLD  , " IR" $,
	CTRY_IRELAND  , ETSI1_WORLD  , " IE" $,
	CTRY_ISRAEL  , NULL1_WORLD  , " IL" $,
	CTRY_ITALY  , ETSI1_WORLD  , " IT" $,
	CTRY_JAMAICA  , FCC3_WORLD  , " JM" $,

	CTRY_JAPAN  , MKK1_MKKA  , " JP" $,
	CTRY_JAPAN1  , MKK1_MKKB  , " JP" $,
	CTRY_JAPAN2  , MKK1_FCCA  , " JP" $,
	CTRY_JAPAN3  , MKK2_MKKA  , " JP" $,
	CTRY_JAPAN4  , MKK1_MKKA1  , " JP" $,
	CTRY_JAPAN5  , MKK1_MKKA2  , " JP" $,
	CTRY_JAPAN6  , MKK1_MKKC  , " JP" $,
	CTRY_JAPAN7  , MKK3_MKKB  , " JP" $,
	CTRY_JAPAN8  , MKK3_MKKA2  , " JP" $,
	CTRY_JAPAN9  , MKK3_MKKC  , " JP" $,
	CTRY_JAPAN10  , MKK4_MKKB  , " JP" $,
	CTRY_JAPAN11  , MKK4_MKKA2  , " JP" $,
	CTRY_JAPAN12  , MKK4_MKKC  , " JP" $,
	CTRY_JAPAN13  , MKK5_MKKB  , " JP" $,
	CTRY_JAPAN14  , MKK5_MKKA2  , " JP" $,
	CTRY_JAPAN15  , MKK5_MKKC  , " JP" $,
	CTRY_JAPAN16  , MKK6_MKKB  , " JP" $,
	CTRY_JAPAN17  , MKK6_MKKA2  , " JP" $,
	CTRY_JAPAN18  , MKK6_MKKC  , " JP" $,
	CTRY_JAPAN19  , MKK7_MKKB  , " JP" $,
	CTRY_JAPAN20  , MKK7_MKKA2  , " JP" $,
	CTRY_JAPAN21  , MKK7_MKKC  , " JP" $,
	CTRY_JAPAN22  , MKK8_MKKB  , " JP" $,
	CTRY_JAPAN23  , MKK8_MKKA2  , " JP" $,
	CTRY_JAPAN24  , MKK8_MKKC  , " JP" $,
	CTRY_JAPAN25  , MKK3_MKKA  , " JP" $,
	CTRY_JAPAN26  , MKK3_MKKA1  , " JP" $,
	CTRY_JAPAN27  , MKK3_FCCA  , " JP" $,
	CTRY_JAPAN28  , MKK4_MKKA1  , " JP" $,
	CTRY_JAPAN29  , MKK4_FCCA  , " JP" $,
	CTRY_JAPAN30  , MKK6_MKKA1  , " JP" $,
	CTRY_JAPAN31  , MKK6_FCCA  , " JP" $,
	CTRY_JAPAN32  , MKK7_MKKA1  , " JP" $,
	CTRY_JAPAN33  , MKK7_FCCA  , " JP" $,
	CTRY_JAPAN34  , MKK9_MKKA  , " JP" $,
	CTRY_JAPAN35  , MKK10_MKKA  , " JP" $,
	CTRY_JAPAN36  , MKK4_MKKA  , " JP" $,
	CTRY_JAPAN37  , MKK9_FCCA  , " JP" $,
	CTRY_JAPAN38  , MKK9_MKKA1  , " JP" $,
	CTRY_JAPAN39  , MKK9_MKKC  , " JP" $,
	CTRY_JAPAN40  , MKK9_MKKA2  , " JP" $,
	CTRY_JAPAN41  , MKK10_FCCA  , " JP" $,
	CTRY_JAPAN42  , MKK10_MKKA1  , " JP" $,
	CTRY_JAPAN43  , MKK10_MKKC  , " JP" $,
	CTRY_JAPAN44  , MKK10_MKKA2  , " JP" $,
	CTRY_JAPAN45  , MKK11_MKKA  , " JP" $,
	CTRY_JAPAN46  , MKK11_FCCA  , " JP" $,
	CTRY_JAPAN47  , MKK11_MKKA1  , " JP" $,
	CTRY_JAPAN48  , MKK11_MKKC  , " JP" $,
	CTRY_JAPAN49  , MKK11_MKKA2  , " JP" $,
	CTRY_JAPAN50  , MKK12_MKKA  , " JP" $,
	CTRY_JAPAN51  , MKK12_FCCA  , " JP" $,
	CTRY_JAPAN52  , MKK12_MKKA1  , " JP" $,
	CTRY_JAPAN53  , MKK12_MKKC  , " JP" $,
	CTRY_JAPAN54  , MKK12_MKKA2  , " JP" $,
	CTRY_JAPAN57  , MKK13_MKKB  , " JP" $,
	CTRY_JAPAN58  , MKK14_MKKA1  , " JP" $,
	CTRY_JAPAN59  , MKK15_MKKA1  , " JP" $,

	CTRY_JORDAN  , ETSI2_WORLD  , " JO" $,
	CTRY_KAZAKHSTAN  , NULL1_WORLD  , " KZ" $,
	CTRY_KOREA_NORTH  , APL9_WORLD  , " KP" $,
	CTRY_KOREA_ROC  , APL9_WORLD  , " KR" $,
	CTRY_KOREA_ROC2  , APL2_WORLD  , " K2" $,
	CTRY_KOREA_ROC3  , APL9_WORLD  , " K3" $,
	CTRY_KUWAIT  , ETSI3_WORLD  , " KW" $,
	CTRY_LATVIA  , ETSI1_WORLD  , " LV" $,
	CTRY_LEBANON  , NULL1_WORLD  , " LB" $,
	CTRY_LIECHTENSTEIN  , ETSI1_WORLD  , " LI" $,
	CTRY_LITHUANIA  , ETSI1_WORLD  , " LT" $,
	CTRY_LUXEMBOURG  , ETSI1_WORLD  , " LU" $,
	CTRY_MACAU  , FCC2_WORLD  , " MO" $,
	CTRY_MACEDONIA  , NULL1_WORLD  , " MK" $,
	CTRY_MALAYSIA  , APL8_WORLD  , " MY" $,
	CTRY_MALTA  , ETSI1_WORLD  , " MT" $,
	CTRY_MEXICO  , FCC1_FCCA  , " MX" $,
	CTRY_MONACO  , ETSI4_WORLD  , " MC" $,
	CTRY_MOROCCO  , APL4_WORLD  , " MA" $,
	CTRY_NEPAL  , APL1_WORLD  , " NP" $,
	CTRY_NETHERLANDS  , ETSI1_WORLD  , " NL" $,
	CTRY_NETHERLANDS_ANTILLES  , ETSI1_WORLD  , " AN" $,
	CTRY_NEW_ZEALAND  , FCC2_ETSIC  , " NZ" $,
	CTRY_NORWAY  , ETSI1_WORLD  , " NO" $,
	CTRY_OMAN  , FCC3_WORLD  , " OM" $,
	CTRY_PAKISTAN  , NULL1_WORLD  , " PK" $,
	CTRY_PANAMA  , FCC1_FCCA  , " PA" $,
	CTRY_PAPUA_NEW_GUINEA  , FCC1_WORLD  , " PG" $,
	CTRY_PERU  , APL1_WORLD  , " PE" $,
	CTRY_PHILIPPINES  , APL1_WORLD  , " PH" $,
	CTRY_POLAND  , ETSI1_WORLD  , " PL" $,
	CTRY_PORTUGAL  , ETSI1_WORLD  , " PT" $,
	CTRY_PUERTO_RICO  , FCC1_FCCA  , " PR" $,
	CTRY_QATAR  , APL1_WORLD  , " QA" $,
	CTRY_ROMANIA  , NULL1_WORLD  , " RO" $,
	CTRY_RUSSIA  , NULL1_WORLD  , " RU" $,
	CTRY_SAUDI_ARABIA  , NULL1_WORLD  , " SA" $,
	CTRY_SERBIA_MONTENEGRO  , ETSI1_WORLD  , " CS" $,
	CTRY_SINGAPORE  , APL6_WORLD  , " SG" $,
	CTRY_SLOVAKIA  , ETSI1_WORLD  , " SK" $,
	CTRY_SLOVENIA  , ETSI1_WORLD  , " SI" $,
	CTRY_SOUTH_AFRICA  , FCC3_WORLD  , " ZA" $,
	CTRY_SPAIN  , ETSI1_WORLD  , " ES" $,
	CTRY_SRI_LANKA  , FCC3_WORLD  , " LK" $,
	CTRY_SWEDEN  , ETSI1_WORLD  , " SE" $,
	CTRY_SWITZERLAND  , ETSI1_WORLD  , " CH" $,
	CTRY_SYRIA  , NULL1_WORLD  , " SY" $,
	CTRY_TAIWAN  , APL3_FCCA  , " TW" $,
	CTRY_THAILAND  , FCC3_WORLD  , " TH" $,
	CTRY_TRINIDAD_Y_TOBAGO  , FCC3_WORLD  , " TT" $,
	CTRY_TUNISIA  , ETSI3_WORLD  , " TN" $,
	CTRY_TURKEY  , ETSI3_WORLD  , " TR" $,
	CTRY_UKRAINE  , NULL1_WORLD  , " UA" $,
	CTRY_UAE  , NULL1_WORLD  , " AE" $,
	CTRY_UNITED_KINGDOM  , ETSI1_WORLD  , " GB" $,
	CTRY_UNITED_STATES  , FCC3_FCCA  , " US" $,

	CTRY_UNITED_STATES_FCC49  , FCC4_FCCA  , " PS" $,
	CTRY_URUGUAY  , FCC3_WORLD  , " UY" $,
	CTRY_UZBEKISTAN  , FCC3_FCCA  , " UZ" $,
	CTRY_VENEZUELA  , APL2_ETSIC  , " VE" $,
	CTRY_VIET_NAM  , NULL1_WORLD  , " VN" $,
	CTRY_YEMEN  , NULL1_WORLD  , " YE" $,
	CTRY_ZIMBABWE  , NULL1_WORLD  , " ZW" $,
here swap - 2 /n* 2 + / constant #allCountries


\ LICENSE_BEGIN
\ Copyright (c) 2011 FirmWorks
\ 
\ Permission is hereby granted, free of charge, to any person obtaining

\ a copy of this software and associated documentation files (the
\ "Software"), to deal in the Software without restriction, including
\ without limitation the rights to use, copy, modify, merge, publish,
\ distribute, sublicense, and/or sell copies of the Software, and to
\ permit persons to whom the Software is furnished to do so, subject to
\ the following conditions:
\ 
\ The above copyright notice and this permission notice shall be
\ included in all copies or substantial portions of the Software.
\ 
\ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
\ EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
\ MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
\ NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
\ LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
\ OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
\ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
\
\ LICENSE_END
