#! /bin/sh
# Converts a collection of .tag files to ctag format

# Usage: toctag BASEDIR file.tag ...

homedir=$1
shift

cat >tags.hdr <<EOF
!_TAG_FILE_FORMAT 1
!_TAG_FILE_SORTED 1
!_TAG_PROGRAM_NAME OpenFirmwareBuilder
!_TAG_PROGRAM_VERSION 1
EOF

sed -e "s,\${BP},${homedir}," $* | LC_ALL=C sort | uniq | cat tags.hdr - >tags
rm tags.hdr

